{{- if and (eq .Values.secrets.provider "static") (not .Values.secrets.existingSecret) }}
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.32.13/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tarka.secretName" . }}
  labels:
    {{- include "tarka.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secrets.data }}
  {{- if $value }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
{{- end }}
