{{- if and (eq .Values.secrets.provider "external") (not .Values.secrets.existingSecret) }}
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ include "tarka.fullname" . }}
  labels:
    {{- include "tarka.labels" . | nindent 4 }}
spec:
  provider:
    aws:
      service: {{ .Values.secrets.externalSecrets.backendType }}
      region: {{ .Values.secrets.externalSecrets.region }}
      {{- if .Values.secrets.externalSecrets.roleArn }}
      role: {{ .Values.secrets.externalSecrets.roleArn }}
      {{- end }}
{{- end }}
