{{- if .Values.serviceAccount.create -}}
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.32.13/serviceaccount-v1.json
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tarka.serviceAccountName" . }}
  labels:
    {{- include "tarka.labels" . | nindent 4 }}
  annotations:
    {{- if eq .Values.serviceAccount.provider "eks-irsa" }}
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.eksRoleArn | quote }}
    {{- end }}
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
