{{- if .Values.ui.enabled }}
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.32.13/service-v1.json
apiVersion: v1
kind: Service
metadata:
  name: {{ include "tarka.ui.fullname" . }}
  labels:
    {{- include "tarka.labels" . | nindent 4 }}
    app.kubernetes.io/component: ui
spec:
  type: {{ .Values.ui.service.type }}
  selector:
    {{- include "tarka.ui.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.ui.service.port }}
      targetPort: http
      protocol: TCP
{{- end }}
